name: get_cli_pro
version: 1.9.1
homepage: https://github.com/jonataslaw/get_cli
description: Official CLI for GetX™ framework to build Flutter and Server
  Applications easily
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ansicolor: ">=2.0.3 <3.0.0"#控制台颜色
  collection: ">=1.19.0 <2.0.0"#集合的处理
  dart_style: ">=2.3.6 <3.0.0" #用于格式化 Dart 代码
  dcli: ">=6.0.5 <7.0.0" # 命令行工具,如输入组件的提示模块
  commander_ui: ^2.4.0 # 命令行工具,如输入组件的提示模块，可用上下左右箭头选择
  http: ">=1.2.2 <2.0.0"#网络请求
  intl: ">=0.19.0 <1.0.0" #国际化
  meta: ">=1.15.0 <2.0.0" # 用于处理元数据
  path: ">=1.9.0  <2.0.0" #用于处理文件路径
  process_run: ">=1.1.0 <2.0.0" #用于查找可执行文件，比如shell命令
  pubspec_parse: ">=1.3.0 <2.0.0" #解析 pubspec.yaml 文件
  pub_semver: ">=2.1.4 <3.0.0" #pub库的版本控制
  recase: ">=4.1.0 <5.0.0" #文本的大小写更改
  version: ">=3.0.2 <4.0.0" #dart库，用于比较和增加版本号
  yaml: ">=3.1.2 <4.0.0" #YAML 的解析器
  archive: ^3.6.1 # 解压
  mason_logger: ^0.3.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8

# 配置标识为 get 包的可执行文件
executables:
  get_cli_pro: get_cli_pro
